name: PEP8
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
      - name: Run autopep8
        run: |
          python -m autopep8 --max-line-length=185 --recursive --diff --exit-code ./irene*
